# Generated by Django 4.1.3 on 2022-11-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situ', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=750)),
                ('pub', models.DateField()),
                ('data_emprestimo', models.DateField(verbose_name='')),
                ('data_devolucao', models.DateField(verbose_name='')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='titulos.situacao')),
            ],
        ),
    ]
