# Generated by Django 4.1.3 on 2022-11-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Situacao',
            new_name='Sit',
        ),
        migrations.RenameField(
            model_name='titulo',
            old_name='situacao',
            new_name='sit',
        ),
    ]
