# Generated by Django 4.1.3 on 2022-11-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulos', '0002_rename_situacao_sit_rename_situacao_titulo_sit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='data_devolucao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='data_emprestimo',
            field=models.DateTimeField(),
        ),
    ]
