# Generated by Django 4.1.3 on 2022-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
